#!/bin/bash
set -x
set -e
gen_dir=$PWD/generated
antlr_path=$PWD/java/antlr-4.7.1-complete.jar
rm -rf $gen_dir
mkdir -p $gen_dir
pushd antlr4
files_python="ANTLRv4Lexer.g4 LexBasic.g4 ANTLRv4Parser.g4"
java -Xmx500M -cp .:$antlr_path:$CLASSPATH org.antlr.v4.Tool $files_python -o $gen_dir -Dlanguage=Python3
popd


